name: ECS CICD
on:
  push:
    branches:
      - dev  
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest 
    if: ${{ !contains(github.event.head_commit.message, '[skip actions]') }}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume:  arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/github-actions
        aws-region: ap-northeast-2  

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Set up Docker Buildx          
      uses: docker/setup-buildx-action@v3
    - name: Build, tag, and push docker image to Amazon ECR Public
      uses: docker/build-push-action@v6
      id: build-image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ec2-team-frontend
        IMAGE_TAG: ${{ github.sha }}
      with:
        push: true
        tags: | 
           ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
           ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:web
        cache-from: type=gha              
        cache-to: type=gha,mode=max

    - name: Checkout Kubernetes manifests repository
      uses: actions/checkout@v4
      with:
        repository: mc-workercloud-ec2/manifest
        ref: main
        token: ${{ secrets.ACTION_TOKEN }}
        path: manifest
  
  
    - name: Update Kubernetes resources
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ec2-team-frontend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        MANIFEST_PATH="manifest/front/deployment.yaml" 
        NEW_IMAGE="$REGISTRY/$REPOSITORY:$IMAGE_TAG"
        sed -i "s|image:*|image: $REGISTRY\/$REPOSITORY:$IMAGE_TAG|" $MANIFEST_PATH
        cat $MANIFEST_PATH
  
    - name: Commit files
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd k8s-manifest-repo
        git config --global user.email "ec2team@multicampus.test"
        git config --global user.name "ec2team"
        git add .
        git commit -m "Update image tag: $IMAGE_TAG"
          git push -u origin main
          
    - name: Post a message in a channel
      uses: slackapi/slack-github-action@v2.0.0
      if: always()
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: incoming-webhook
        payload: |
          blocks:
            - type: "section"
              text:
                type: "mrkdwn"
                text: "<@channel> Front Build 결과: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      
